/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.apl.sha.ers.model.User;

/** 
 * MyEclipse Struts
 * Creation date: 01-15-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/getOneWayCtns.jsp"
 */
public class DistributionDepotAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	
	/** 
	 * alloc depot 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int blnumber = 0;
		try {
			blnumber = Integer.parseInt(request.getParameter("blnumber").trim());
			User user = this.getUser(request);
			if (user == null) {
				return mapping.findForward("login");
			}
			process.distributionDepot(blnumber, user);
		} catch (Exception e) {
			// TODO: handle exception
		}
		return mapping.findForward("success");
	}
}