/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.apl.sha.ers.model.BookingReference;
import common.Logger;

/** 
 * MyEclipse Struts
 * Creation date: 01-15-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/getOneWayCtns.jsp"
 */
public class GetBLByReferAction extends BaseAction {
	
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String res = "";
		try{
			res = request.getParameter("referenceNo");
			if(res!=null && !res.trim().equals("")){
				List<BookingReference> list = process.getBlByReferNo(res.toUpperCase());
				request.setAttribute("refereMess", list);
				request.setAttribute("referenNo", res);
			}
		}catch(Exception e){
			if(e!=null && e.getMessage()!=null)
			{
				System.out.println(e.getMessage());
			}
			return this.errorHandle(mapping, request, "error.object.notfound", new Object[] {getMessage(request, "refereceNo.displayname"),res});
		}
		return mapping.findForward("success");
	}
}